services:
  mysql80:
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    container_name: enterprise-subsidy.mysql80
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    # Oracle-packaged version includes a `linux/arm64/v8` version, needed for
    # machines with Apple Silicon CPUs (Mac M1, M2)
    image: mysql:8.0.33-oracle
    networks:
      - devstack_default
    volumes:
      - enterprise_subsidy_mysql80:/var/lib/mysql

  memcache:
    image: memcached:1.6.6
    container_name: enterprise-subsidy.memcache
    networks:
      - devstack_default
    command: memcached -vv

  app:
    image: edxops/enterprise-subsidy-dev
    container_name: enterprise-subsidy.app
    volumes:
      - .:/edx/app/enterprise-subsidy
      - ../src:/edx/src
    command: bash -c 'while true; do python /edx/app/enterprise-subsidy/manage.py runserver 0.0.0.0:18280; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: enterprise_subsidy.settings.devstack
      ENABLE_DJANGO_TOOLBAR: 1
    ports:
      - "18280:18280"
    networks:
      - devstack_default
    stdin_open: true
    tty: true
    depends_on:
      - mysql80
      - memcache

  consume_learner_credit_course_enrollment_lifecycle:
    image: edxops/enterprise-subsidy-dev
    container_name: enterprise-subsidy.consume_learner_credit_course_enrollment_lifecycle
    volumes:
      - .:/edx/app/enterprise-subsidy
      - ../src:/edx/src
    command: bash -c 'while true; do python /edx/app/enterprise-subsidy/manage.py consume_events -t learner-credit-course-enrollment-lifecycle -g enterprise_subsidy_dev; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: enterprise_subsidy.settings.devstack
    ports:
      - "18281:18281"
    networks:
      - devstack_default
    stdin_open: true
    tty: true
    depends_on:
      - mysql80
      - memcache

networks:
  devstack_default:
    external: true

volumes:
  enterprise_subsidy_mysql80:
